### ISSUE TITLE
你好 可以设置导航栏间距吗  还有  在页面左右滑动的时候     定位的时候  没有动画  谢谢

### ISSUE THREAD

**Issue by 18667366881** [HuyangJake/YJSliderView#3]
你好 可以设置导航栏间距吗  还有  在页面左右滑动的时候     定位的时候  没有动画  谢谢

**Comment by HuyangJake** [comment]
* 可以设置 `maxCountInScreen`属性来控制一屏展示title的个数
* 页面通过手势滑动是有动画的，最新代码中取消了点击title后的动画（需要的话可以下载历史的release版本或者自行修改）

**Comment by 18667366881** [comment]
您好   顶部导航栏的按钮是按照数量自动计算的吗   这个可以自定义设置间距多少吗  谢谢

**Comment by HuyangJake** [comment]
是的，按照数量自动计算，两个那妞之间的距离至少30.暂时还没有公开属性修改。之后会考虑添加进去可配置

**Comment by 18667366881** [comment]
你好  viewForItemAtIndex   方法中 如何给 SliderContentViewController 控制器 传递 当前可见的title  或者 标志
我想实现导航条切换时的事件   动态传递给 一个 控制器

**Comment by HuyangJake** [comment]
Demo中的SliderContentViewController只是用了它的view。需要给不同tab页的controller传递不同的状态可以在viewForItemAtIndex中给Controller公开的属性赋值。还有不清楚可以添加我的QQ：527609121

**Comment by 18667366881** [comment]
好的 谢谢
