### ISSUE TITLE
view如果包含输入框，布局会出错。

### ISSUE THREAD

**Issue by jopinfly** [HuyangJake/YJSliderView#7]
会显示
The behavior of the UICollectionViewFlowLayout is not defined because:
 the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
有什么解决办法吗~

**Comment by HuyangJake** [comment]
你好，感谢选择使用YJSliderView。

看着像是你自定义的View内容超出了我们item的大小了，先检查下布局，应该不是输入框的问题。感觉是SliderView里的问题，可以把这部分代码邮件发给我看下。
希望你能解决问题。

**Comment by jopinfly** [comment]
你好，感谢回复~
最后是因为和我的侧滑库有点冲突了，已经解决了~
